package uiswing;

import controlador.ControladorAgenda;
import dominio.agenda.Contacto;
import dominio.agenda.TipoContacto;
import dominio.agenda.TipoTelefono;
import dominio.usuario.UsuarioAgenda;
import java.util.List;
import javax.swing.JOptionPane;
import vista.VistaAgenda;

public class CrearContacto extends javax.swing.JDialog implements VistaAgenda {

    private ControladorAgenda controlador;
    
    public CrearContacto(java.awt.Frame parent, boolean modal, UsuarioAgenda usuario) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorAgenda(usuario, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Nombre = new javax.swing.JLabel();
        lbl_Telefono = new javax.swing.JLabel();
        lbl_Tipo_Contacto = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        cmb_Tipo_Contacto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_Contactos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JButton();
        lbl_TipoTelefono = new javax.swing.JLabel();
        cmb_Tipo_Telefono = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Nombre.setText("Nombre:");

        lbl_Telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Telefono.setText("Teléfono:");

        lbl_Tipo_Contacto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Tipo_Contacto.setText("Tipo de Contacto:");

        txt_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_Telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmb_Tipo_Contacto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jScrollPane1.setViewportView(lst_Contactos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Contactos");

        btn_Agregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        lbl_TipoTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TipoTelefono.setText("Tipo de Teléfono:");

        cmb_Tipo_Telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_Telefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_Tipo_Contacto, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lbl_TipoTelefono))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_Tipo_Contacto, 0, 185, Short.MAX_VALUE)
                                    .addComponent(cmb_Tipo_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btn_Agregar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmb_Tipo_Contacto, cmb_Tipo_Telefono});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Nombre)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Telefono)
                            .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tipo_Contacto)
                            .addComponent(cmb_Tipo_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TipoTelefono)
                            .addComponent(cmb_Tipo_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btn_Agregar))
                    .addComponent(jScrollPane1))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        String nombre = txt_Nombre.getText();
        String telefono = txt_Telefono.getText();
        TipoContacto tipoContacto = (TipoContacto) cmb_Tipo_Contacto.getSelectedItem();
        TipoTelefono tipoTelefono = (TipoTelefono) cmb_Tipo_Telefono.getSelectedItem();
        
        controlador.crearContacto(nombre, telefono, tipoTelefono, tipoContacto);
    }//GEN-LAST:event_btn_AgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JComboBox<Object> cmb_Tipo_Contacto;
    private javax.swing.JComboBox<Object> cmb_Tipo_Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Telefono;
    private javax.swing.JLabel lbl_TipoTelefono;
    private javax.swing.JLabel lbl_Tipo_Contacto;
    private javax.swing.JList<Object> lst_Contactos;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Telefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarTipoContacto(List<TipoContacto> tipoContactos) {
        for (TipoContacto tipoContacto : tipoContactos) {
            cmb_Tipo_Contacto.addItem(tipoContacto);
        }
    }

    @Override
    public void cargarTipoTelefono(List<TipoTelefono> tipoTelefonos) {
        for (TipoTelefono tipoTelefono : tipoTelefonos) {
            cmb_Tipo_Telefono.addItem(tipoTelefono);
        }
    }

    @Override
    public void mostrarContactos(List<Contacto> contactos) {
        lst_Contactos.setListData(contactos.toArray());
    }

    @Override
    public void mostrarTitulo(String mensaje) {
        setTitle(mensaje);
    }
    
    @Override
    public void limpiarDatos() {
        txt_Nombre.setText("");
        txt_Telefono.setText("");
        cmb_Tipo_Contacto.setSelectedIndex(0);
        cmb_Tipo_Telefono.setSelectedIndex(0);
        txt_Nombre.requestFocus();
    }

    @Override
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(
                    rootPane,
                    mensaje,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
    }
}
