package uiswing;

import dominio.EventoSistema;
import dominio.Sistema;
import dominio.trabajador.Sesion;
import dominio.trabajador.UsuarioAdministrador;
import dominio.trabajador.UsuarioAgenda;
import java.util.ArrayList;
import java.util.List;
import observer.Observable;
import observer.Observador;

public class MonitorUsuariosConectados extends javax.swing.JDialog implements Observador {

    private UsuarioAdministrador usuarioAdministrador;
    
    public MonitorUsuariosConectados(
            java.awt.Frame parent,
            boolean modal,
            UsuarioAdministrador usuarioAdministrador) {

        super(parent, modal);
        initComponents();
        this.usuarioAdministrador = usuarioAdministrador;
        this.setTitle("Monitor de " + usuarioAdministrador.getNombreCompleto());
        mostrarLista();
        Sistema.getInstancia().agregar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lst_usuarios_logueados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lst_usuarios_logueados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lst_usuarios_logueados;
    // End of variables declaration//GEN-END:variables

    private void mostrarLista() {
        List<Sesion> usuariosLogueados = Sistema.getInstancia().getLogueados();
        List<String> listadoLogueados = new ArrayList<>();
        String linea = null;
        for (Sesion usuarioLogueado : usuariosLogueados) {
            linea = formatear(usuarioLogueado);
            listadoLogueados.add(linea);
        }
        
        String[] listadoFormatArray = new String[listadoLogueados.size()];
        lst_usuarios_logueados.setListData(listadoLogueados.toArray(listadoFormatArray));
    }

    private String formatear(Sesion sesion) {
        UsuarioAgenda usuarioAgenda = (UsuarioAgenda) sesion.getUsuario();
        return usuarioAgenda.getNombreCompleto() + " (" +
                usuarioAgenda.getCantidadContactosAgenda() + ")" + " - " +
                sesion.getFechaUltimoIngreso();
                
    }

    @Override
    public void actualizar(Observable origen, Object evento) {
        if (evento.equals(EventoSistema.LOGIN)) {
            mostrarLista();
        }
    }
}
