package uiswing;

import dominio.EventoSistema;
import dominio.Sistema;
import dominio.sistema.Sector;
import java.util.ArrayList;
import java.util.List;
import observer.Observable;
import observer.Observador;

public class MonitorLlamadas extends javax.swing.JDialog implements Observador {
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        let_sectors_list = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(let_sectors_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> let_sectors_list;
    // End of variables declaration//GEN-END:variables

    private void mostrarLista() {
        List<Sector> sectoresTotal = Sistema.getInstancia().getSectores();
        List<String> listaSectoresArr = new ArrayList<>();
        String linea = null;
        for(Sector sector : sectoresTotal){
            linea = formatear(sector);
            listaSectoresArr.add(linea);
        }
        
        String[] listadoFormatArray = new String[listaSectoresArr.size()];
        let_sectors_list.setListData(listaSectoresArr.toArray(listadoFormatArray));
    }

    private String formatear(Sector sector) {
        return sector.getNombre();
                
    }

    @Override
    public void actualizar(Observable origen, Object evento) {
        if (evento.equals(EventoSistema.LOGIN)) {
            mostrarLista();
        }
    }
}
