/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uiswing;

import javax.swing.JOptionPane;

/**
 *
 * @author alumnoFI
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnu_Principal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnu_item_LoginAgenda = new javax.swing.JMenuItem();
        mnu_item_LoginAdministrador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnu_item_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Principal");

        mnu_item_LoginAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_item_LoginAgenda.setText("Login Agenda");
        mnu_item_LoginAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_item_LoginAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_item_LoginAgenda);

        mnu_item_LoginAdministrador.setText("Login Administrador");
        mnu_item_LoginAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_item_LoginAdministradorActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_item_LoginAdministrador);

        mnu_Principal.add(jMenu1);

        jMenu2.setText("Aplicación");

        mnu_item_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu_item_Salir.setText("Salir");
        mnu_item_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_item_SalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnu_item_Salir);

        mnu_Principal.add(jMenu2);

        setJMenuBar(mnu_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_item_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_item_SalirActionPerformed
        salir();
    }//GEN-LAST:event_mnu_item_SalirActionPerformed

    private void mnu_item_LoginAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_item_LoginAgendaActionPerformed
        Login login = new LoginAgenda(this, false);
        login.setVisible(true);
    }//GEN-LAST:event_mnu_item_LoginAgendaActionPerformed

    private void mnu_item_LoginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_item_LoginAdministradorActionPerformed
        Login login = new LoginAdministrador(this, false);
        login.setVisible(true);
    }//GEN-LAST:event_mnu_item_LoginAdministradorActionPerformed

    private void salir() {
        int opcion = JOptionPane.showConfirmDialog(this, "Desea Salir?");
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mnu_Principal;
    private javax.swing.JMenuItem mnu_item_LoginAdministrador;
    private javax.swing.JMenuItem mnu_item_LoginAgenda;
    private javax.swing.JMenuItem mnu_item_Salir;
    // End of variables declaration//GEN-END:variables
}
